name: 'Build DocC Documentation'
description: 'Builds the DocC documentation for the project'
inputs:
  scheme:
    description: 'The scheme to build the documentation for'
    required: true
    default: 'MyFramework'
  output:
    description: 'The output directory for the documentation'
    required: true
    default: './docs'
  platform:
    description: 'The platform to build the documentation for [macos, ios, watchos, tvos]'
    required: true
    default: 'macos'
runs:
  using: 'composite'
  steps:
    - name: 'Build DocC Documentation'
      shell: bash
      run: $GITHUB_ACTION_PATH/build-docc.sh ${{ inputs.scheme }} ${{ inputs.output }} ${{ inputs.platform }}